# Generated by Django 5.2.8 on 2025-11-17 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalaEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('en_mantenimiento', models.BooleanField(default=False)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_reservante', models.CharField(max_length=12)),
                ('hora_inicio', models.DateTimeField(auto_now_add=True)),
                ('hora_termino', models.DateTimeField()),
                ('sala_reservada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva_salas.salaestudio')),
            ],
        ),
    ]
